[package]
name = "rust-echo"
version = "0.1.0"
authors = ["zhengshuxin"]
edition = "2018"

[dependencies]
master = { path = "../../master" }
log = "0.4.0"
env_logger = "0.6.0"
log4rs = "0.8.1"
getopt = "0.3.9"
getopts = "0.2.18"
